# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 07:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=256)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('key_words', models.CharField(blank=True, max_length=256)),
                ('author_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_answeres', to=settings.AUTH_USER_MODEL, verbose_name='Author of answer')),
                ('author_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_queries', to=settings.AUTH_USER_MODEL, verbose_name='Author of query')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('section', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Section')),
            ],
        ),
    ]
