# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('response', models.TextField()),
            ],
        ),
    ]
